version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ph_backend
    restart: unless-stopped
    volumes:
      - ./backend/database.db:/app/backend/database.db
    networks:
      - traefik # Assumes you have a network named 'traefik_proxy' for Traefik
    # Labels for Traefik - uncomment and adapt to your domain
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.ph-backend.rule=Host(`your-domain.com`) && PathPrefix(`/api`)"
    #   - "traefik.http.routers.ph-backend.entrypoints=websecure"
    #   - "traefik.http.routers.ph-backend.tls.certresolver=myresolver"
    #   - "traefik.http.services.ph-backend.loadbalancer.server.port=5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ph_frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - traefik
    # Labels for Traefik - uncomment and adapt to your domain
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.ph-frontend.rule=Host(`your-domain.com`)"
    #   - "traefik.http.routers.ph-frontend.entrypoints=websecure"
    #   - "traefik.http.routers.ph-frontend.tls.certresolver=myresolver"
    #   - "traefik.http.services.ph-frontend.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
